siteConfig:
  title: Supersymmetry
  # url: https://example.com
  author: Matthew Pence
  email: matt@ohiosveryown.co
  description: Write an awesome description for your new site here. You can edit this line in saber-config.yml. It will appear in your document head meta (for Google search results) site description.

plugins:
  - resolve: saber-plugin-query-posts